### ISSUE TITLE
sidekiq-iteration vs job-iteration

### ISSUE THREAD

**Issue by dylanz** [fatkodima/sidekiq-iteration#3]
What are the differences between `sidekq-iteration` and Shopify's `job-iteration`?  It would be helpful if the `README` covered that!

**Comment by fatkodima** [comment]
Yeah, but the only real difference is that it does not depend on `ActiveJob` and is designed to work with raw `sidekiq`.
It currently has nested iterator for quite some time (https://github.com/fatkodima/sidekiq-iteration#nested-iteration), but there is a PR in the `job-iteration` (https://github.com/Shopify/job-iteration/pull/310) that will be merged soon.
And the gem's usage API is a little bit different, but basically the same.

**Comment by dylanz** [comment]
@fatkodima... ahhhh... that makes sense!  Thanks for the quick reply 🥳
